---
- name: include appserver specific varibales
  include_vars: "appserver.yml"
  tags: installation

- name: run appserver service
  command: "docker run -it -d --name appserver -p 5001:5001 {{ image_name }}"
